name: Actions Workflow

on:
  repository_dispatch:
    types: [ Dispatch ]
  push:
    branches:
      - main
#      - 'dev'
#      - '!feature/**'
    tags:
      - 'v**'
      - '!v1.0'
#    # Careful or wont trigger at all
#    paths:
#      - '**.py'
#      - .github/**
#      - '!docs/**'
#      - '!test.js'
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
#  schedule:
#    - cron: "15 14 * * *"
#    - cron: "15 21 * * *"

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: list things
        run: |
          pwd
          ls
          echo ${GITHUB_SHA}
          echo ${GITHUB_SHA::8}
          echo ${GITHUB_REF}
          echo ${GITHUB_REPOSITORY}
          echo ${GITHUB_WORKSPACE}

      - name: Dispatch Output
        run: 'echo "field: ${{ github.event.client_payload.version }}"'

#      - name: simple JS actions
#        id: greet
#        uses: actions/hello-world-javascript-action@main
#        with:
#          who-to-greet: 'Mona the Octocat'
#
#      - name: LogGreeting
#        run: echo "${{ steps.greet.outputs.time }}"

  multi-os:
    needs: run-github-actions
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, ubuntu-18.04, ubuntu-16.04 ]
#        os: [ windows-latest, ubuntu-latest, macos-latest ]

    steps:
      - name: test all shells
        run: echo 'Hello World'

      - name: OS version
        run: |
          cat /etc/os-release
