name: Actions Workflow

on:
  repository_dispatch:
    types: [ Dispatch ]
  push:
    branches:
      - main
#      - 'dev'
#      - '!feature/**'
    tags:
      - 'v**'
      - '!v1.0'
#    # Careful or wont trigger at all
#    paths:
#      - '**.py'
#      - .github/**
#      - '!docs/**'
#      - '!test.js'
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
#  schedule:
#    - cron: "15 14 * * *"
#    - cron: "15 21 * * *"

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: List Things
        id: list-things
        run: |
          pwd
          ls
          echo ${GITHUB_SHA}
          echo ${GITHUB_SHA::8}
          echo ${GITHUB_REF}
          echo ${GITHUB_REPOSITORY}
          echo ${GITHUB_WORKSPACE}

      - name: Dispatch Output
        id: Dispatch_Output
        run: 'echo "field: ${{ github.event.client_payload.version }}"'

      - name: Simple JS actions
        id: greet
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: 'Mona the Octocat'

      - name: Log Greeting
        run: echo "${{ steps.greet.outputs.time }}"

      - name: failure
        id: failure
        run: |
          echo "Error!" 1>&2
          exit 64

      - name: Failure notification
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#githubactions_notifications'
        if: always()
#        if: cancelled() || failure()

  multi-os:
    needs: run-github-actions
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, ubuntu-18.04, ubuntu-16.04 ]
#        os: [ windows-latest, ubuntu-latest, macos-latest ]
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - name: test all shells
        id: test-shells
        run: echo 'Hello World'

      - name: OS version
        id: os-version
        run: |
          cat /etc/os-release

      - name: Failure Notification
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#githubactions_notifications'
        if: always()
#        if: cancelled() || failure()
