name: Actions Runner Controller Demo
on:
  push:
    branches:
      - dev
      - main
  workflow_dispatch:
    branches:
      - dev
      - main

env:
  RUNNER: ${{ vars.RUNNER }}

jobs:
  Explore-GitHub-Actions:
    runs-on: ${{ env.RUNNER }}
    environment: 
      name: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
    steps:
    - run: echo "🎉 This job uses runner scale set runners!"