name: Actions Runner Controller Demo
on:
  push:
    branches:
      - dev
      - main
  workflow_dispatch:
    branches:
      - dev
      - main

jobs:
  Explore-GitHub-Actions:
    strategy:
      matrix:
        env: [prod, dev]
        include:
          - env: prod
            runner: arc-runner-set-01
          - env: dev
            runner: arc-runner-set-02
    runs-on: ${{ matrix.runner }}
    environment: 
      name: ${{ matrix.env }}
    steps:
    - run: echo "🎉 This job uses runner scale set runners!"